USE md2;

CREATE TABLE LopHoc (
MaLop INT PRIMARY KEY,
TenLop VARCHAR(150) NOT NULL,
NamHoc VARCHAR(9)
);

CREATE TABLE SinhVien (
MaSV INT PRIMARY KEY,
MaLop INT,
HoVaTen VARCHAR(255),
NgaySinh DATE NOT NULL,
FOREIGN KEY (MaLop) REFERENCES LopHoc(MaLop)
);