USE md2;

CREATE TABLE Classes ( 
MaLop INT PRIMARY KEY,
TenLop VARCHAR(150) NOT NULL,
NamHoc VARCHAR(9) NOT NULL
);

CREATE TABLE Students ( 
MaSV INT PRIMARY KEY,
MaLop INT, 
HoVaTen VARCHAR(250) NOT NULL,
NgaySinh DATE,
GioiTinh VARCHAR(5),
FOREIGN KEY (MaLop) REFERENCES Classes(MaLop)
);
